version: 2
jobs:
  test:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - add_ssh_keys:
          fingerprints:
            - "98:5b:b5:28:ba:fa:99:a9:f8:f9:7b:ce:94:2b:1c:fa"

      - run: git config user.name circleci
      - run: yarn predeploy
      - run: yarn deploy
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
